### ISSUE TITLE
Split out Catalog Definitions into a seperate CRD

### ISSUE THREAD

**Issue by fhennig** [stackabletech/trino-operator#13]
This is done when
- [ ] [ADR019](https://docs.stackable.tech/home/contributor/adr/ADR019-trino_catalog_definitions.html) & [ADR020](https://docs.stackable.tech/home/contributor/adr/ADR020-trino_catalog_usage.html) are implemented
- [ ] tests have been added
- [ ] documentation has been added
- [ ] examples have been added
- [ ] feature tracker has been updated (@lfrancke can help)

**Comment by maltesander** [comment]
done in https://github.com/stackabletech/trino-operator/pull/263
