### ISSUE TITLE
Support specifying a namespace to watch

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/trino-operator#137]
Currently this operator watches resources in all namespaces.
I'd like this to be configurable so I can specify which namespace to watch.

This should be a `clap` argument (which then can be provided on the command line or in an env var) called `--watch-namespace`.
It is okay to only take a single namespace for now.

- [ ] Implement the above description
- [ ] Document the default behavior and the new parameter

See https://github.com/stackabletech/issues/issues/162 for the overarching epic

**Comment by maltesander** [comment]
I dont think it makes sense to tag another regorule operator, so this is blocked by https://github.com/stackabletech/opa-operator/pull/244 because of the regorule dependency.
