### ISSUE TITLE
Document service discovery

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/trino-operator#138]
As a user of services deployed by this operator I'd like to know how to discover its connection details.

It's done when

- documentation is available on all the objects (e.g. ConfigMaps) created by this operator and the circumstances under which they are created and
- documentation on the contents of the created objects is available.

NOTE: This ticket is part of an epic and autocreated for all our operators. It _might_ not apply to this operator in particular, in that case please comment and close
https://github.com/stackabletech/documentation/issues/86

**Comment by maltesander** [comment]
The Trino operator currently does not provide any discovery.
