### ISSUE TITLE
Implement resource requests and limits for Trino pods

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/trino-operator#248]
Part of this epic https://github.com/stackabletech/issues/issues/241

### Acceptance criteria

- [x] Resource requests and limits are configurable in CRD using the [common structs](https://github.com/stackabletech/operator-rs/blob/e56110dd394c98a67f21ff17f7fab6c88f3aa322/src/commons/resources.rs#L77) from operator-rs
- [x] Resource requests and limits are configured for Kubernetes pods
- [x] Resource requests and limits are configured in the product (e.g. "-Xmx" etc. for Java based images)
- [x] Adapt/Add integration tests to specify and test correct amount of resources
- [x] Adapt/Add examples
- [x] Adapt documentation: New section in `usage.adoc` with product specific information and link to common shared resources concept
- [x] Optional: Use sensible defaults for each role (if reasonable and applicable) and document accordingly in `usage.adoc`
- [x] Code contains useful comments
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)
- [ ] Feature Tracker has been updated
- [ ] Followup tickets have been created if needed (e.g. to update demos)

**Comment by lfrancke** [comment]
Does it make sense to include this in a demo?

**Comment by sbernauer** [comment]
As it's in 22.09 we could do that. I tried all the demos and they worked perfectly fine with the default resources. I would try to not increase them as the demos should run everywhere. But happy to discuss
