### ISSUE TITLE
Trino Authentication V1

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/trino-operator#26]
Trino has multiple authentication types: https://trino.io/docs/current/security/authentication-types.html

In this epic I'd like to track the implementation of these types:

- [x] Password file: https://trino.io/docs/current/security/password-file.html
- [x] LDAP: https://trino.io/docs/current/security/ldap.html

They are closely related because in the end they both check a username and password against a data source.
The problem with LDAP will be - I assume - the integration tests as they will need some kind of LDAP service to be available.

**Comment by fhennig** [comment]
LDAP authentication has been implemented by now.

**Comment by fhennig** [comment]
@lfrancke Can this be closed?

**Comment by lfrancke** [comment]
Yes, thank you!
