### ISSUE TITLE
Documentation: Add more extensive documentation on how to add catalogs to Trino instances

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/trino-operator#274]
#263 implemented the TrinoCatalog feature which allows configuring catalogs for Trino via reusable objects (TrinoCatalog).

The documentation changes in that PR are fairly minimal and don't explain the fundamental concept of how these are linked and play together.

We should add a section to the documentation that explains:
- what a TrinoCatalog objects is 
- how a TrinoCatalog object is linked with a TrinoCluster

Acceptance criteria:
- [ ] there exists a concept page that explains how the TrinoCatalog works
- [ ] there exists a guide page on how to use it

**Comment by fhennig** [comment]
Alright, so far we have just put everything in the usage.adoc, but there is this ticket https://github.com/stackabletech/documentation/issues/227 to improve on this. 

There are four aspects to fullfil to document a feature like this ideally:
- **Concept** - explain the CRD, how it relates to the TrinoCluster, why it was introduced and why in this way
- **Tutorial** - A simple tutorial to deploy a toy catalog in the most simple way, in a controlled toy cluster to explain how it works. looking at trino and seeing the catalog in the WebUI (if that's a thing)
- **Guide** - A guide on how to use this in production. This should help someone make use of the TrinoCatalog for _their_ setup that they already have. The guide necessarily needs to cover many "if"s and "when"s. It should leave the user with something that is production ready, not a toy example like in a tutorial. It should include best practices
- **Reference** - A reference page to exhaustively explain all the CRD options that are in the resource, and what they are for. This is something we want to generate in the future.

For now, I believe that a Concept page and a Guide page is most important. I don't think we need a tutorial for every little feature, I'd rather add more platform-level tutorials that show of a set of features together, which can then be linked if someone wants to learn hands on about the TrinoCluster CRD. But a conceptual explanation, as well as an exhausitve guide for a production ready setup is a must I believe.

**Comment by fhennig** [comment]
Acceptance criteria:
- [ ] there exists a concept page that explains how the TrinoCatalog works
- [ ] there exists a guide page on how to use it

**Comment by maltesander** [comment]
There are soon four connectors supported (https://github.com/stackabletech/trino-operator/pull/293). Just for completeness:
* https://trino.io/docs/current/connector/hive.html[Hive]
* https://trino.io/docs/current/connector/iceberg.html[Iceberg]
* https://trino.io/docs/current/connector/tpcds.html[TPCDS]
* https://trino.io/docs/current/connector/tpch.html[TPCH]

**Comment by adwk67** [comment]
> There are soon four connectors supported (#293). Just for completeness:
> 
> * [https://trino.io/docs/current/connector/hive.html[Hive]](https://trino.io/docs/current/connector/hive.html%5BHive%5D)
> * [https://trino.io/docs/current/connector/iceberg.html[Iceberg]](https://trino.io/docs/current/connector/iceberg.html%5BIceberg%5D)
> * [https://trino.io/docs/current/connector/tpcds.html[TPCDS]](https://trino.io/docs/current/connector/tpcds.html%5BTPCDS%5D)
> * [https://trino.io/docs/current/connector/tpch.html[TPCH]](https://trino.io/docs/current/connector/tpch.html%5BTPCH%5D)

Ok, I'll include those in the PR.

**Comment by lfrancke** [comment]
None of the boxes have been ticked. Have both been done?

**Comment by adwk67** [comment]
Both have been done and the boxes are now checked.
