### ISSUE TITLE
Support Iceberg connector

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/trino-operator#285]
Should be trivial as it's basically the same as the Hive connector
CRD is the same as Hive
https://trino.io/docs/current/connector/iceberg.html

- [ ] Docs added
- [ ] Tests added

**Comment by lfrancke** [comment]
@sbernauer @soenkeliebau Do you think this warrants an entry in the Feature Tracker?
I tend to say "yes"

**Comment by sbernauer** [comment]
I would tend to no but i don't care. The only other product we have that can do iceberg is spark. Trino has lots of catalogs we can add ;)

**Comment by soenkeliebau** [comment]
I think this is really Trino specific, yeah ...

**Comment by lfrancke** [comment]
The feature tracker can support product specific features but that doesn't mean we have to add it. It'sa ll good. We'll leave it off.
