### ISSUE TITLE
LDAP Secret resolution not working correctly

### ISSUE THREAD

**Issue by fhennig** [stackabletech/trino-operator#366]
### Affected version

current

### Current and expected behavior

LDAP secret should be resolved with k8sSearch but the name is taken from the SecretClass

### Possible solution

We'll implement framework functionality for it

### Would you like to work on fixing this bug?

None

**Comment by fhennig** [comment]
https://github.com/stackabletech/trino-operator/blame/17ed2e48f2b0d1e850711b4d5489f77369e6e44e/rust/operator-binary/src/controller.rs#L661

**Comment by lfrancke** [comment]
Is this a bug in other operators as well or limited to Trino?

**Comment by fhennig** [comment]
It was only here
