### ISSUE TITLE
Support worker graceful shutdown

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/trino-operator#429]

**Comment by predator4ann** [comment]
Hello, how is the progress of this feature? Thank you.

**Comment by sbernauer** [comment]
Hi @predator4ann, so far we have not found the time to work on this, as no user has requested this feature so far.
Are you running into the problem of queries failing and need this feature?

**Comment by sbernauer** [comment]
Hi @predator4ann I just wanted to give a heads up that this feature is implemented and will be available in 23.11 :)

**Comment by predator4ann** [comment]
Got it, thanks for informing.
