### ISSUE TITLE
High availability for Trino client endpoint

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/trino-operator#490]
Trino client connect using HTTP to the coordinator to run SQL queries. Implement and document how to run providing a high availability endpoint for resilience.

**Comment by sbernauer** [comment]
Just for the record: Trino does not provide a HA setup (you can only have a single coordinator). https://github.com/stackabletech/trino-lb can help to improve the situation though

**Comment by Jimvin** [comment]
I'll close this issue given there's no HA support in Trino coordinator at this time.
