### ISSUE TITLE
428 version - /bin/bash: openssl: command not found

### ISSUE THREAD

**Issue by dshershov** [stackabletech/trino-operator#492]
### Affected version

428

### Current and expected behavior

After upgrade from 414 to 428 prepare container for worker and coordinator was ran with a problem
```
/bin/bash: openssl: command not found
```
Image version:
```
    productVersion: "428"
    stackableVersion: 0.0.0-dev
```

<img width="554" alt="screenshot 2023-10-27 in 14 20 38" src="https://github.com/stackabletech/trino-operator/assets/17449010/791c0402-bd9b-49d4-839a-627000be3f01">

### Would you like to work on fixing this bug?

None

**Comment by sbernauer** [comment]
Hi @dshershov,

i assume you are using trino-operator version 23.7?
Version 23.7 of the trino-operator does not support nightly versions of the images (as you pull in by using `stackableVersion: 0.0.0-dev`).
You need to use
```
    productVersion: "414"
    stackableVersion: "23.7"
```
to pull in the corresponding image version for the operator. Please note that as the time 23.7 was released, only Trino versions up to 414 were supported.

The alternative would be to also use the nightly version for trino-operator as well, but please be aware that both - trino-operator and trino image in version 0.0.0-dev - are under active development and breaking changes can occur anytime.

**Comment by dshershov** [comment]
Hello @sbernauer !
Glad to see you :)
hmm, okay
So, you not recommend to use 428 version of trino now? I need to work with OPA and I try to configuration role model with filterResources which I think cannot available with old trino-opa-authorizer integration

**Comment by lfrancke** [comment]
We plan to make a new release in November which will include a newer version of Trino.

Until then, as @sbernauer said, you'd need to use the nightly versions of the operator.

**Comment by dshershov** [comment]
oh, sounds good @lfrancke 
Thanks a lot team!

**Comment by sbernauer** [comment]
Yeah, as @lfrancke mentioned I think going with nightly and Trino 428 is a valid option (or wait 3-4 weeks) ;)
https://github.com/stackabletech/trino-operator/issues/443 might provide some valuable information, especially https://github.com/sbernauer/trino/blob/add-open-policy-agent/plugin/trino-open-policy-agent/src/test/resources/trino.rego.
We have plans to make authorization easier for users, until then you have to hand-craft the regorules similar to the link I send.

**Comment by dshershov** [comment]
WOAH!
This information is really useful for us! Thanks a lot, Sebastian!
