### ISSUE TITLE
[NEW VERSION] Trino 438

### ISSUE THREAD

**Issue by maltesander** [stackabletech/trino-operator#524]
**Which new version of Trino should we support?**

438 (or better 439 if released)

Our latest supported is 428.

**Additional information**

Changelog https://trino.io/docs/current/release/release-438.html

**Changes required**

436 (required)
- Require JDK 21.0.1 to run Trino https://github.com/trinodb/trino/issues/20010

434 (check for usage in iceberg)
- Disallow invalid configuration options. Previously, they were silently ignored https://github.com/trinodb/trino/issues/19735
- Remove support for legacy table statistics tracking https://github.com/trinodb/trino/issues/19803

**Notes**

I just built 438 as custom image in experimental and there were a couple of things to do, just to keep it here:

***docker-images***
- use default storage connector (no custom image for 438)
- remove opa authorizer from docker image (for 438, need switch for older versions)
- add java 21 to trino for 438 and to java-base

***trino-operator***
- set opa.allow-permission-management-operations=true for views / grants in opa config (access-control properties, need switch for version 428/438)
- adapt JVM properties https://trino.io/docs/current/installation/deployment.html#jvm-config (need switch for version 428/438 because of different jdk version)

remarks:
- opa config / access-control properties can not be overridden / properties added
- JVM configs hardcoded can only be overridden completly 

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update and test getting started guide with updated version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by paulpaul1076** [comment]
When do you plan to release this? They fixed the slow execution of "select count(*)" in trino 430, I am looking forward to this release.

**Comment by maltesander** [comment]
Hi @paulpaul1076 we will introduce Trino version 436 in the Stackable 24.3 release line. The image maybe available earlier in the nightly / 0.0.0-dev version.

**Comment by paulpaul1076** [comment]
@maltesander thanks! When do you plan to make this release? Soon, or in several months?

**Comment by soenkeliebau** [comment]
We should try to go to 437 directly, as this has been released in the interim.

Release notes

**Comment by maltesander** [comment]
@soenkeliebau as discussed today it will be at least 438 for OPA? I can adapt title etc then...

**Comment by soenkeliebau** [comment]
I think you can, yes. As far as I can see 438 should be released later today..

**Comment by maltesander** [comment]
Ok will wait for release notes and update after.

**Comment by maltesander** [comment]
Hi @paulpaul1076,

we now have Trino 438 in our nexus https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable%2Ftrino%2Ftags%2F438-stackable0.0.0-dev

Due to a Java bump and some authorizer changes you have to use the 0.0.0-dev operator to run this. It will be available and stable in the next release coming in march 2024.

Malte

**Comment by paulpaul1076** [comment]
@maltesander  Thanks for the update!

**Comment by paulpaul1076** [comment]
@maltesander what do you think about waiting a little bit and including the version of Trino that supports Iceberg views?

As you may know, Iceberg is the native table format for Trino. And they're about to release a new important feature: Iceberg views, here's the pull request:

https://github.com/trinodb/trino/pull/19818

According to Daniel Weeks from Tabular, they're just waiting for Iceberg 1.5.0 release to go through (the vote is happening right now and it should be out this week).

**Comment by maltesander** [comment]
Hi @paulpaul1076,
for now 438 (which is there already) and probably the latest 439 will make the 24.3 release.

For that specific PR we need to discuss internally, i cannot promise it. But we release dev/experimental versions if there are interesting features that users are interested in.

**Comment by paulpaul1076** [comment]
@maltesander I am very interested in this feature. :) Cool, thank you!

**Comment by paulpaul1076** [comment]
@maltesander we're also having this discussion https://github.com/orgs/stackabletech/discussions/41 it turns out that stackable Trino doesn't (at least officially it seems) support rest catalog for Iceberg, which is the native and recommended catalog. Do you think it's possible to add it in the next release?

**Comment by lfrancke** [comment]
Just FYI that we will not release 438 but 439 instead in the next version.
