### ISSUE TITLE
[NEW VERSION] Trino 449-450

### ISSUE THREAD

**Issue by sdasdasd1** [stackabletech/trino-operator#604]
**Which new version of Trino should we support?**

449-450
**Additional information**

We really need to use iceberg views in our iceberg REST catalog. And support of this was added in Trino 449
**Changes required**

Are there any upstream changes that we need to support?
Views in Iceberg REST catalog https://github.com/trinodb/trino/pull/19818

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update and test getting started guide with updated version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by lfrancke** [comment]
Thank you for raising this issue.
Our next SDP release, due in July (24.7), will include at least 449.

**Comment by sdasdasd1** [comment]
@lfrancke Thank you for the answer! Is there an approximate date? Is it the beginning or the end of July?

**Comment by lfrancke** [comment]
We're aiming for mid- to end of July.
But you can expect dev images for this to appear sooner than that. We'll update this ticket.

**Comment by maltesander** [comment]
Added trino version 451 for release 24.07 here https://github.com/stackabletech/trino-operator/pull/609
