### ISSUE TITLE
Trino version is not shown in UI or when querying version()

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/trino-operator#648]
### Affected Stackable version

24.7.0

### Affected Trino version

451

### Current and expected behavior

The version of Trino running is not displayed where expected in the coordinator web UI. In addition, when the version() function is run in a SQL statement it returns an empty string rather than the expected result i.e. the Trino version number.

The latter of these issues causes issues with some clients since they attempt to enumerate the Trino version and the connection can fail when they are unable to do so.

### Would you like to work on fixing this bug?

None

### Tasks

- [ ] https://github.com/stackabletech/docker-images/pull/881
- [ ] https://github.com/stackabletech/trino-operator/pull/650

**Comment by lfrancke** [comment]
Issue is not closed. Can it be?

**Comment by sbernauer** [comment]
Yes, sorry
